spring.application.name=Nutriai


server.port=1003

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/nutriai
spring.datasource.username=root
spring.datasource.password=@sumit222
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver